[build]
  base = "frontend/ProductListApplication"
  publish = "dist"
  command = "npm ci && npm run build"

[[redirects]]

  from = "/api/*"
  to = "https://productlist-case-study.onrender.com/:splat"
  status = 200


