[build]
  base = "frontend/ProductListApplication"
  publish = "frontend/ProductListApplication/dist"
  command = "npm ci && npm run build"

[[redirects]]
  # Replace the placeholder with your Render backend base URL AFTER backend deploy
  # Example: https://stajcase-api.onrender.com
  from = "/api/*"
  to = "https://RENDER_BACKEND_URL/:splat"
  status = 200


